### ISSUE TITLE
Multiple Drones with one gui

### ISSUE THREAD

**Issue by ProcessorGuy** [ElishaAz/simple_airsim#2]
Hello, 

I wanted to simulate drone swarms by using this code. Is it possible?  I tried the following code but it didn't work out.

------------------------------------------------------------
def square(drone: Drone):
    drone.takeoff(True)
    while True:
        for i in range(4):
            drone.move_by(50, 0, 0, True)
            drone.turn_by(0, 0, 90, True)
        time.sleep(0.1)

if \__name__ == '\__main\__':

    # UAV Swarm size
    UAVNum = 4
    
    # pool size
    pool_size = UAVNum  
    
    # define worker function before a Pool is instantiated
    def worker(item):
        try:
            xx = "man{}".format(item)
            yy = "gui{}".format(item)
            with Manager(coordinate_system.AIRSIM, method=square) as xx:
                with GUIManager(man, 10, 10, 10, 3) as yy:
                    yy.start()            
        except:
            print('error with item')  

    pool = Pool(pool_size)
    
    for ii in range(1, UAVNum+1, 1):
        pool.apply_async(worker, (ii,))

    pool.close()
    pool.join()    

------------------------------------------------------------

How can we fix it?

**Comment by ElishaAz** [comment]
Sorry, but this is not supported.
